name = "hono-blog-demo"
compatibility_date = "2024-09-16"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"
[vars]
USERNAME = "lyh"
PASSWORD = "liuyuhe"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
[[kv_namespaces]]
binding = "BLOG_DEMO"
id = "a88d15674d33432ab88ce10aaf7619e2"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"